logging:
  level:
    root: debug
    org:
      springframework:
        web: debug
      hibernate: error
    security:
      acl: debug
spring:
  profile: default
  datasource:
    url: jdbc:h2:mem:testdb2;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialize: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2
      enabled: true
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000